# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0226d6b9853d958f057d643fa80e0d24eceff21eeb9bab3078676927fea5770880dd0f877207bfba613f9adcbcf0f815837c523ad272238d5e2ea093ed74c4af

test:
  secret_key_base: df6ab6c5d3d3002ea2030d77f2a52e122f4484ad364335674d2935a1de480f9dee82d75cdbd4c5c9a1f228e49bee5743f510abefc9a4ab2d05a118106f425d18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
